name: pre-commit tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  # Enable manual running of workflow, so we can force execution
  workflow_dispatch:

jobs:
  # The specific pre-commit tests configurations are found in
  # the .pre-commit-config.yaml file at the root of the repository
  preliminary_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: set PY (hash of installed Python version)
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit tests
      run: |
        pip install pre-commit
        pre-commit run --all-files

  build_test_and_upload:
    needs: preliminary_test
    runs-on: macos-latest
    steps: 
    - uses: actions/checkout@v5
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        brew update
        brew install pandoc
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Build install and test package
      run: |
        python -m pip install --upgrade pip setuptools wheel build
        python -m build
        ls -la dist
        pip install dist/copy_oocyst_prediction-*any.whl
        predict_oocysts -h
    - name: Upload wheels
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v5
      with:
        name: copy_oocyst_prediction
        path: dist/copy_oocyst_prediction-*any.whl
